//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace open_api_client.OpenApiMessageConsumerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/1.0", ConfigurationName="OpenApiMessageConsumerServiceReference.OpenApiMessageConsumerServicePortType")]
    public interface OpenApiMessageConsumerServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetMessageRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        open_api_client.OpenApiMessageConsumerServiceReference.GetMessageResponse GetMessage(open_api_client.OpenApiMessageConsumerServiceReference.GetMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageRequest", WrapperNamespace="urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/types/1.0", IsWrapped=true)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/types/1.0", Order=0)]
        public System.Xml.XmlElement Message;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(System.Xml.XmlElement Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageResponse", WrapperNamespace="urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/types/1.0", IsWrapped=true)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-gnivc-ru/inplat/servin/OpenApiMessageConsumerService/types/1.0", Order=0)]
        public System.Xml.XmlElement Message;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(System.Xml.XmlElement Message) {
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OpenApiMessageConsumerServicePortTypeChannel : open_api_client.OpenApiMessageConsumerServiceReference.OpenApiMessageConsumerServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenApiMessageConsumerServicePortTypeClient : System.ServiceModel.ClientBase<open_api_client.OpenApiMessageConsumerServiceReference.OpenApiMessageConsumerServicePortType>, open_api_client.OpenApiMessageConsumerServiceReference.OpenApiMessageConsumerServicePortType {
        
        public OpenApiMessageConsumerServicePortTypeClient() {
        }
        
        public OpenApiMessageConsumerServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpenApiMessageConsumerServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenApiMessageConsumerServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenApiMessageConsumerServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public open_api_client.OpenApiMessageConsumerServiceReference.GetMessageResponse GetMessage(open_api_client.OpenApiMessageConsumerServiceReference.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
    }
}
